apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
    stack: labs
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/hpa-example
        envFrom:
        - configMapRef:
            name: toto
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
status: {}
---
apiVersion: v1
data:
  toto: toto
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: toto
